export const movieFormInputs = [
  {
    id: "title",
    name: "title",
    type: "text",
    placeholder: "Title",
    label: "Title",
    required: true,
  },
  {
    id: "plot",
    name: "plot",
    as: "textarea",
    rows: 2,
    label: "Plot",
    required: true,
  },
  {
    id: "genres",
    name: "genres",
    type: "text",
    placeholder: "Genres",
    label: "Genres",
    required: true,
  },
  {
    id: "directors",
    name: "directors",
    type: "text",
    placeholder: "Directors",
    label: "Directors",
    required: true,
  },
  {
    id: "cast",
    name: "cast",
    type: "text",
    placeholder: "Cast",
    label: "Cast",
    required: true,
  },
  {
    id: "runtime",
    name: "runtime",
    type: "number",
    placeholder: "Runtime",
    label: "Runtime",
    required: true,
  },
  {
    id: "poster",
    name: "poster",
    type: "text",
    placeholder: "Poster",
    label: "Poster",
  },
  {
    id: "fullplot",
    name: "fullplot",
    as: "textarea",
    rows: 4,
    label: "Full Plot",
  },
  {
    id: "languages",
    name: "languages",
    type: "text",
    placeholder: "Languages",
    label: "Languages",
  },
  {
    id: "released",
    name: "released",
    type: "date",
    label: "Released",
  },
  {
    id: "rated",
    name: "rated",
    type: "text",
    placeholder: "Rated",
    label: "Rated",
  },
  {
    id: "year",
    name: "year",
    type: "number",
    placeholder: "Year",
    label: "Year",
  },
  {
    id: "imdb",
    name: "imdb",
    type: "number",
    placeholder: "IMDB",
    label: "IMDB",
    min: 0,
    max: 10,
  },
  {
    id: "tomatoes",
    name: "tomatoes",
    type: "number",
    placeholder: "Rotten Tomatoes",
    label: "Rotten Tomatoes",
    min: 0,
    max: 100,
  },
  {
    id: "countries",
    name: "countries",
    type: "text",
    label: "Countries",
    placeholder: "Countries",
  },
];
